apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-db-secret
  namespace: demo
  labels:
    app.kubernetes.io/name: demo-db
    app.kubernetes.io/managed-by: backstage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: demo-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/mysql/${{ parameters.name }}
        property: password