apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: postgresql-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .n8n_user }}"
        password: "{{ .n8n_password }}"
  data:
  - secretKey: n8n_user
    remoteRef:
      key: postgresql
      property: n8n-user
  - secretKey: n8n_password
    remoteRef:
      key: postgresql
      property: n8n-password
