apiVersion: apps/v1
kind: Deployment
metadata:
  name: chores-frontend
  namespace: chores-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chores-frontend
  template:
    metadata:
      labels:
        app: chores-frontend
    spec:
      imagePullSecrets:
      - name: ecr-registry
      containers:
      - name: chores-frontend
        image: 852893458518.dkr.ecr.us-east-2.amazonaws.com/chores-frontend:bafbff0bd7e3265b3d15259a7e3952c966420116
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: API_URL
