---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-agent-audit-web
  namespace: agent-audit
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: k8s-secrets
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: agent-audit-web
          serviceAccountRef:
            name: eso-agent-audit-web
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-agent-audit-web-db
  namespace: agent-audit
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: k8s-secrets
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: agent-audit-web-db
          serviceAccountRef:
            name: eso-agent-audit-web-db
