apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: chores-db
  namespace: chores-backend
spec:
  providerConfigRef:
    name: mysql-provider
  forProvider:
    name: {}
---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: User
metadata:
  name: chores-user
  namespace: chores-backend
spec:
  providerConfigRef:
    name: mysql-provider
  forProvider:
    passwordSecretRef:
      name: chores-mysql-credentials
      key: DB_PASSWORD
      namespace: chores-tracker
---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: chores-backend-db-grant
  namespace: chores-backend
spec:
  providerConfigRef:
    name: mysql-provider
  forProvider:
    databaseRef:
      name: chores-db
    privileges:
      - ALL
    userRef:
      name: chores-user
