apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chores-tracker-secrets
  namespace: chores-tracker
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: chores-mysql-credentials
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: chores-mysql-credentials        
        property: DB_NAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: chores-mysql-credentials        
        property: DB_PASSWORD
    - secretKey: DB_USER
      remoteRef:
        key: chores-mysql-credentials        
        property: DB_USER
