apiVersion: batch/v1
kind: Job
metadata:
  name: chores-tracker-migrate
  namespace: chores-tracker
  labels:
    argocd.argoproj.io/instance: chores-tracker
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: chores-tracker-migrate
    spec:
      containers:
        - name: migrate
          image: 852893458518.dkr.ecr.us-east-2.amazonaws.com/chores-tracker:alembic-2
          command: ["./entrypoint.sh", "migrate"]
          workingDir: /app
          env:
            - name: DB_HOST
              value: mysql.mysql.svc.cluster.local
            - name: DB_PORT
              value: '3306'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: chores-mysql-credentials
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: chores-mysql-credentials
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_NAME
                  name: chores-mysql-credentials
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      imagePullSecrets:
        - name: ecr-registry
      restartPolicy: Never