apiVersion: v1
kind: Service
metadata:
  name: chores-tracker-backend  # Changed from chores-tracker
  namespace: chores-tracker
spec:
  ports:
    - name: http
      port: 8000  # Changed to actual backend port
      protocol: TCP
      targetPort: 8000
  selector:
    app: chores-tracker-backend
  type: ClusterIP