apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql
  namespace: postgresql
  annotations:
    agent-docs/path: docs.md
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app=postgresql'
    backstage.io/kubernetes-namespace: postgresql
  tags: [database, stateful, pgvector]
spec:
  type: infrastructure
  lifecycle: production
  owner: group:default/platform
  system: default/platform-data
  dependsOn:
    - resource:vault/vault
