---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agent-audit-web-db-credentials
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-agent-audit-web-db
    kind: SecretStore
  target:
    name: agent-audit-web-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: audit-user
      remoteRef:
        key: agent-audit-web-db
        property: db-user
    - secretKey: audit-password
      remoteRef:
        key: agent-audit-web-db
        property: db-password
    - secretKey: audit-database
      remoteRef:
        key: agent-audit-web-db
        property: db-name
