apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-mysql-2-secret
  namespace: test-mysql
  labels:
    app.kubernetes.io/name: test-mysql-2
    app.kubernetes.io/instance: test-mysql-2-mysql
    app.kubernetes.io/component: database-secret
    app.kubernetes.io/part-of: test-mysql-2
    environment: development
    backstage.io/kubernetes-id: test-mysql-2
  annotations:
    backstage.io/kubernetes-id: test-mysql-2
    backstage.io/kubernetes-namespace: test-mysql
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: test-mysql-2-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Database password from Vault
        DB_PASSWORD: "{{ .password | toString }}"
  data:
    - secretKey: password
      remoteRef:
        key: test-mysql-2/DB_PASSWORD