apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-mysql-mysql-db
  description: MySQL database for test-mysql
  annotations:
    backstage.io/kubernetes-id: test-mysql
    backstage.io/kubernetes-namespace: test-mysql
spec:
  type: database
  owner: group:default/platform-team
  system: system:default/examples
  lifecycle: development