apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yml: |
    tunnel: homelab-k3s
    credentials-file: /etc/cloudflared/creds/token
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    protocol: auto
    ingress:
      - hostname: "*.arigsela.com"
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: "arigsela.com"
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - service: http_status:404