apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: mysql
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mysql-credentials
    creationPolicy: Owner
    type: Opaque
  data:
    - secretKey: password
      remoteRef:
        key: mysql
        property: root-password
    - secretKey: user
      remoteRef:
        key: mysql
        property: username
    - secretKey: database
      remoteRef:
        key: mysql
        property: database-name