apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: dns
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: dns
      nodePort: 31061
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: dns-udp
      nodePort: 31061
    - name: pihole-http
      port: 80
      targetPort: pihole-http
      nodePort: 30007
      protocol: TCP
  selector:
    app: pihole
  externalTrafficPolicy: Local