apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testmysql-secret
  namespace: testmysql
  labels:
    app.kubernetes.io/name: testmysql
    app.kubernetes.io/instance: testmysql-mysql
    app.kubernetes.io/component: database-secret
    app.kubernetes.io/part-of: testmysql
    environment: development
    backstage.io/kubernetes-id: testmysql
  annotations:
    backstage.io/kubernetes-id: testmysql
    backstage.io/kubernetes-namespace: testmysql
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: testmysql-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Database password from Vault
        DB_PASSWORD: "{{ .password | toString }}"
  data:
    - secretKey: password
      remoteRef:
        key: testmysql/DB_PASSWORD