apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: testmysql
  labels:
    app.kubernetes.io/name: testmysql
    app.kubernetes.io/instance: testmysql-vault
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: testmysql
    environment: development
    backstage.io/kubernetes-id: testmysql
  annotations:
    backstage.io/kubernetes-id: testmysql
    backstage.io/kubernetes-namespace: testmysql
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"