apiVersion: apps/v1
kind: Deployment
metadata:
 name: chores-backend-deployment
spec:
 selector:
   matchLabels:
     run: chores-backend-deployment
 replicas: 1
 template:
   metadata:
     labels:
       run: chores-backend-deployment
   spec:
     imagePullSecrets:
     - name: regcred
     containers:
     - name: chores-backend
       image: 852893458518.dkr.ecr.us-east-2.amazonaws.com/chores-backend
       imagePullPolicy: Always
       envFrom:
        - configMapRef:
            name: chores-app-config
       env:
       - name: DB_PASSWORD
         valueFrom:
         secretKeyRef:
          name: chores-app-secrets
          key: DB_PASSWORD
       ports:
       -  containerPort: 8000
          name: http
          protocol: TCP
       resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m


