apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-workflows-s3-creds
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: argo-workflows-s3-creds
    creationPolicy: Owner
  data:
    - secretKey: accessKey
      remoteRef:
        key: argo-workflows/s3
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: argo-workflows/s3
        property: secretKey
