---
# Source: ai-platform-engineering/charts/backstage-plugin-agent-forge/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-platform-backstage-forge
  labels:
    helm.sh/chart: backstage-plugin-agent-forge-0.1.0
    app.kubernetes.io/name: backstage-forge
    app.kubernetes.io/instance: ai-platform
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
