apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: mysqltest
  labels:
    app.kubernetes.io/name: mysqltest
    app.kubernetes.io/instance: mysqltest-vault
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: mysqltest
    environment: development
    backstage.io/kubernetes-id: mysqltest
  annotations:
    backstage.io/kubernetes-id: mysqltest
    backstage.io/kubernetes-namespace: mysqltest
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"