apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homelab-agent-db
  namespace: kagent
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab-agent-db
    kind: SecretStore
  target:
    name: homelab-agent-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MEMORY_DB_URL: "postgresql://homelab_agent:{{ .password }}@postgresql.postgresql.svc.cluster.local:5432/homelab_agent"
  data:
    - secretKey: password
      remoteRef:
        key: homelab-agent-db
        property: password
