apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asela1-asela1
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/arigsela/kubernetes
    targetRevision: main
    path: base-apps/asela1-asela1
  destination:
    server: https://kubernetes.default.svc
    namespace: asela1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true