apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asela3-asela3
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/arigsela/kubernetes
    targetRevision: main
    path: base-apps/asela3-asela3
  destination:
    server: https://kubernetes.default.svc
    namespace: asela3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true