apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argo-cd
spec:
  project: default
  source:
    chart: crossplane-stable
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.19.0-rc.0.110.g0d806babb
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true