apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-cnpg
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/arigsela/kubernetes
    targetRevision: feature/cloudnativepg
    path: base-apps/postgresql-cnpg
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
