apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-prod-db
  namespace: argo-cd
  labels:
    app.kubernetes.io/managed-by: backstage
spec:
  project: default
  source:
    repoURL: https://github.com/arigsela/kubernetes
    targetRevision: main
    path: base-apps/prod-prod-db
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true