---
# Source: ai-platform-engineering/charts/agent-argocd/templates/mcp-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ai-platform-agent-argocd-mcp
  labels:
    helm.sh/chart: agent-argocd-0.3.2
    app.kubernetes.io/name: agent-argocd
    app.kubernetes.io/instance: ai-platform
    app.kubernetes.io/version: "0.3.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ai-platform-agent-argocd-mcp
    app.kubernetes.io/component: mcp
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: agent-argocd
    app.kubernetes.io/instance: ai-platform
    app.kubernetes.io/name: ai-platform-agent-argocd-mcp
    app.kubernetes.io/component: mcp
