apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`vault.arigsela.com`)
    kind: Rule
    services:
    - name: vault
      port: 8200
  tls:
    certResolver: letsencrypt
    domains:
      - main: vault.arigsela.com
