apiVersion: platform.io/v1alpha1
kind: MySQLDatabase
metadata:
  name: test-app-db
  namespace: test-app
spec:
  compositionRef:
    name: xmysqldatabase.platform.io
  parameters:
    databaseName: testapp-db
    username: testapp-user
    userNamespace: test-app
    databaseNamespace: test-app
    privileges:
      - "SELECT"
      - "INSERT"
      - "UPDATE"
      - "DELETE"
      - "CREATE"
      - "DROP"
      - "INDEX"
    passwordSecretRef:
      name: test-app-db-secret
      key: DB_PASSWORD
      namespace: test-app
  writeConnectionSecretToRef:
    name: test-app-db-connection