apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: asela-test2-secret
  namespace: asela-test2
  labels:
    app.kubernetes.io/name: asela-test2
    app.kubernetes.io/instance: asela-test2-mysql
    app.kubernetes.io/component: database-secret
    app.kubernetes.io/part-of: asela-test2
    environment: staging
    backstage.io/kubernetes-id: asela-test2
  annotations:
    backstage.io/kubernetes-id: asela-test2
    backstage.io/kubernetes-namespace: asela-test2
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: asela-test2-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: asela-test2
        property: DB_PASSWORD
