apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crossplane
  template:
    metadata:
      labels:
        app: crossplane
    spec:
      containers:
      - name: crossplane
        image: crossplane/crossplane:v1.18.1-stable
        command:
          - crossplane
        args:
          - core
          - start
          - --webhook-tls-cert-dir=/certs
          - --disable-webhook-server=true
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
      volumes:
        - name: certs
      serviceAccountName: crossplane
