apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weather-kitchen-backend
  namespace: weather-kitchen
  annotations:
    agent-docs/path: docs.md
    backstage.io/kubernetes-label-selector: 'app=weather-kitchen-backend'
    backstage.io/kubernetes-namespace: weather-kitchen
  tags: [fastapi, jwt, postgresql]
spec:
  type: service
  lifecycle: production
  owner: group:default/platform
  system: default/weather-kitchen
  providesApis:
    - default/weather-kitchen-backend-api
  dependsOn:
    - resource:vault/vault
