apiVersion: platform.io/v1alpha1
kind: MySQLDatabase
metadata:
  name: asela5
  namespace: asela5
  labels:
    backstage.io/kubernetes-id: asela5
    app.kubernetes.io/managed-by: backstage
  annotations:
    # Required for discovery
    terasky.backstage.io/add-to-catalog: "true"

    # Entity metadata
    terasky.backstage.io/system: "asela-apps"
    terasky.backstage.io/owner: "team:platform"
    terasky.backstage.io/component-type: "resource"
    terasky.backstage.io/lifecycle: "production"
    terasky.backstage.io/description: "MySQL database for asela5 application"
    terasky.backstage.io/tags: "database,mysql,crossplane,infrastructure"
    backstage.io/kubernetes-id: asela5
    backstage.io/kubernetes-namespace: asela5
spec:
  compositionRef:
    name: xmysqldatabase.platform.io
  parameters:
    databaseName: asela5db
    username: asela5user
    userNamespace: asela5
    databaseNamespace: asela5
    privileges:
      ["SELECT","INSERT","UPDATE","DELETE"]
    passwordSecretRef:
      name: asela5-secret
      key: DB_PASSWORD
      namespace: asela5
  writeConnectionSecretToRef:
    name: asela5-connection
