apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chores-tracker-frontend
  namespace: chores-tracker-frontend
  annotations:
    agent-docs/path: docs.md
    backstage.io/kubernetes-label-selector: 'app=chores-tracker-frontend'
    backstage.io/kubernetes-namespace: chores-tracker-frontend
  tags: [nginx, htmx, frontend]
spec:
  type: website
  lifecycle: production
  owner: group:default/platform
  system: default/chores-tracker
  consumesApis:
    - default/chores-tracker-backend-api
  dependsOn:
    - component:chores-tracker/chores-tracker-backend
