# Backstage Component for smoketest-v11
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smoketest-v11
  description: "Managed via XApplication Composition"
  annotations:
    github.com/project-slug: arigsela/kubernetes
    backstage.io/kubernetes-id: smoketest-v11
  tags:
    - crossplane
    - xapplication
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-engineering
  system: platform
