apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vcluster
  namespace: vcluster-sandbox-1
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: sandbox-1.vcluster.arigsela.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vcluster
                port:
                  number: 443
