apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-db-secret
  namespace: prod
  labels:
    app.kubernetes.io/name: prod-db
    app.kubernetes.io/managed-by: backstage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: prod-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/mysql
        property: password