#!/usr/bin/env python3
"""Generate the Grafana "Cluster Overview" dashboard ConfigMap.

Writes base-apps/logging/grafana-dashboard-cluster-overview.yaml. Edit the panel
definitions here and regenerate; never hand-edit the JSON in the ConfigMap.

    python scripts/gen-cluster-overview-dashboard.py --repo-root .          # write
    python scripts/gen-cluster-overview-dashboard.py --repo-root . --check  # CI

Layout is computed: each section starts where the previous one ended, so adding a
section never means renumbering the ones below it.

Every query must return data against the live Prometheus before it lands here. The
per-pod pressure panels read the kubelet's PSI metrics (KubeletPSI, GA in k8s 1.36),
which cAdvisor exports as container_pressure_{cpu,memory,io}_{waiting,stalled}_seconds_total.
"waiting" is PSI "some" (at least one task stalled), "stalled" is "full".
"""
import argparse
import json
import sys
from pathlib import Path

OUT = Path("base-apps/logging/grafana-dashboard-cluster-overview.yaml")
DS = {"type": "prometheus"}  # the default Prometheus datasource, like the Istio dashboard

HEADER = '''# "Cluster Overview" dashboard, in Grafana's Kubernetes folder.
#
# GENERATED by scripts/gen-cluster-overview-dashboard.py. Do not hand-edit the JSON;
# change the generator and regenerate. CI runs it with --check.
#
# The ConfigMap name is historical. grafana-deployment.yaml mounts it at
# /var/lib/grafana/dashboards/k8s (provider "kubernetes" in
# grafana-dashboard-configmap.yaml). Until 2026-09-24 it existed only in the
# cluster, restored by Velero with a single empty `placeholder` key. It is
# adopted into git under the same name so Grafana's pod spec does not change.
#
# Where the numbers come from (nothing extra is deployed for most of it):
#   - k3s version:        kubernetes_build_info (Prometheus scrapes the API server
#                         and every kubelet; git_version = "v1.36.4+k3s1")
#   - node details:       kube_node_info / kube_node_status_* from the
#                         kube-state-metrics bundled in Coroot's cluster agent
#   - containers, PVCs:   cAdvisor + kubelet metrics (prometheus-config.yaml)
#   - pod pressure:       per-container PSI from the kubelet (KubeletPSI, GA 1.36)
#   - Argo:               argocd_app_info
#   - host CPU/mem/disk:  node_* from Alloy's prometheus.exporter.unix
#                         (alloy-config.yaml), remote-written to Prometheus
#
# Datasources are referenced as {"type": "prometheus"}, i.e. the default
# Prometheus datasource, like the Istio dashboard.
'''


class Builder:
    def __init__(self):
        self.panels = []
        self.y = 0
        self.next_id = 0

    def _id(self):
        self.next_id += 1
        return self.next_id

    def row(self, title):
        self.panels.append({"type": "row", "title": title, "id": self._id(), "collapsed": False,
                            "gridPos": {"h": 1, "w": 24, "x": 0, "y": self.y}, "panels": []})
        self.y += 1

    def line(self, height, cells):
        """Place panels side by side on one line; cells = [(width, add_fn), ...]."""
        x = 0
        for width, add in cells:
            add({"h": height, "w": width, "x": x, "y": self.y})
            x += width
        assert x <= 24, f"line overflows the grid: {x}"
        self.y += height

    # --- panel factories: each returns fn(gridPos) so a line() can place it -------------

    @staticmethod
    def _tgt(expr, legend="", instant=False, fmt=None, ref="A"):
        t = {"datasource": DS, "expr": expr, "refId": ref, "legendFormat": legend}
        if instant:
            t.update({"instant": True, "range": False})
        if fmt:
            t["format"] = fmt
        return t

    @staticmethod
    def _thr(steps):
        return {"mode": "absolute", "steps": [{"color": c, "value": v} for c, v in steps]}

    def stat(self, title, expr, legend="", steps=None, unit="none", text="value", desc=""):
        def add(pos):
            self.panels.append({
                "type": "stat", "title": title, "id": self._id(), "datasource": DS, "description": desc,
                "gridPos": pos, "targets": [self._tgt(expr, legend, instant=True)],
                "fieldConfig": {"defaults": {"unit": unit, "thresholds": self._thr(steps or [("green", None)]),
                                             "color": {"mode": "thresholds"}}, "overrides": []},
                "options": {"reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
                            "textMode": text, "colorMode": "background", "graphMode": "none",
                            "justifyMode": "center"}})
        return add

    def ts(self, title, targets, unit="none", desc="", maxv=None):
        def add(pos):
            d = {"unit": unit, "custom": {"lineWidth": 1, "fillOpacity": 10, "showPoints": "never"}}
            if maxv is not None:
                d["max"] = maxv
                d["min"] = 0
            self.panels.append({
                "type": "timeseries", "title": title, "id": self._id(), "datasource": DS, "description": desc,
                "gridPos": pos, "targets": [self._tgt(e, lg, ref=r) for e, lg, r in targets],
                "fieldConfig": {"defaults": d, "overrides": []},
                "options": {"legend": {"displayMode": "table", "placement": "right", "calcs": ["lastNotNull", "max"]},
                            "tooltip": {"mode": "multi", "sort": "desc"}}})
        return add

    def bargauge(self, title, expr, legend, unit="percent", steps=None, desc=""):
        def add(pos):
            self.panels.append({
                "type": "bargauge", "title": title, "id": self._id(), "datasource": DS, "description": desc,
                "gridPos": pos, "targets": [self._tgt(expr, legend, instant=True)],
                "fieldConfig": {"defaults": {"unit": unit, "min": 0, "max": 100,
                                             "thresholds": self._thr(steps or [("green", None), ("yellow", 75), ("red", 90)]),
                                             "color": {"mode": "thresholds"}}, "overrides": []},
                "options": {"orientation": "horizontal", "displayMode": "gradient", "showUnfilled": True,
                            "reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False}}})
        return add

    def table(self, title, expr, keep, rename, desc=""):
        def add(pos):
            self.panels.append({
                "type": "table", "title": title, "id": self._id(), "datasource": DS, "description": desc,
                "gridPos": pos, "targets": [self._tgt(expr, "", instant=True, fmt="table")],
                "transformations": [{"id": "organize", "options": {
                    "excludeByName": {}, "includeByName": {k: True for k in keep},
                    "indexByName": {k: i for i, k in enumerate(keep)}, "renameByName": rename}}],
                "fieldConfig": {"defaults": {}, "overrides": []},
                "options": {"showHeader": True, "cellHeight": "sm"}})
        return add


def build():
    b = Builder()

    # --- Versions -------------------------------------------------------------------
    b.row("Versions")
    b.line(4, [
        (6, b.stat("API server version", 'kubernetes_build_info{job="kubernetes-apiservers"}',
                   legend="{{git_version}}", text="name", steps=[("blue", None)],
                   desc="k3s/Kubernetes version the API server reports (kubernetes_build_info.git_version).")),
        (4, b.stat("Distinct k8s versions", "count(count by (git_version) (kubernetes_build_info))",
                   steps=[("green", None), ("orange", 2)],
                   desc="1 = every node and the API server run the same version. >1 = version skew, expected only mid-upgrade.")),
        (3, b.stat("Nodes", "count(kube_node_info)", steps=[("blue", None)])),
        (4, b.stat("Nodes not Ready",
                   'count(kube_node_info) - sum(kube_node_status_condition{condition="Ready",status="true"})',
                   steps=[("green", None), ("red", 1)])),
        (3, b.stat("Cordoned nodes", "sum(kube_node_spec_unschedulable)", steps=[("green", None), ("orange", 1)],
                   desc="Non-zero during an upgrade hop (system-upgrade-controller cordons each worker).")),
        (4, b.stat("Running pods", 'sum(kubelet_running_pods{job="kubernetes-nodes"})', steps=[("blue", None)])),
    ])
    b.line(5, [
        (24, b.table("Nodes", "kube_node_info",
                     ["node", "kubelet_version", "os_image", "kernel_version", "container_runtime_version", "internal_ip"],
                     {"node": "Node", "kubelet_version": "k3s / kubelet", "os_image": "OS", "kernel_version": "Kernel",
                      "container_runtime_version": "Container runtime", "internal_ip": "IP"},
                     desc="Per-node versions from kube_node_info (kube-state-metrics bundled in Coroot's cluster agent).")),
    ])

    # --- Node resources (host metrics from Alloy's unix exporter) ------------------------
    b.row("Node resources (host)")
    b.line(8, [
        (12, b.ts("CPU used %",
                  [('100 * (1 - avg by (node) (rate(node_cpu_seconds_total{mode="idle"}[5m])))', "{{node}}", "A")],
                  unit="percent", maxv=100)),
        (12, b.ts("Memory used %",
                  [("100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)", "{{node}}", "A")],
                  unit="percent", maxv=100)),
    ])
    b.line(7, [
        (8, b.bargauge("Root filesystem used %",
                       '100 * (1 - node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})',
                       "{{node}}",
                       desc="local-path PVs live on each node's root filesystem, so this is also PVC headroom.")),
        (8, b.ts("Load (1m) per core",
                 [('node_load1 / on (node) count by (node) (node_cpu_seconds_total{mode="idle"})', "{{node}}", "A")])),
        (8, b.stat("Node uptime", "time() - node_boot_time_seconds", legend="{{node}}", unit="s",
                   steps=[("blue", None)], text="value_and_name")),
    ])
    b.line(8, [
        (12, b.ts("Disk I/O",
                  [("sum by (node) (rate(node_disk_read_bytes_total[5m]))", "{{node}} read", "A"),
                   ("sum by (node) (rate(node_disk_written_bytes_total[5m]))", "{{node}} write", "B")],
                  unit="Bps")),
        (12, b.ts("CPU pressure (some, % time stalled)",
                  [("100 * rate(node_pressure_cpu_waiting_seconds_total[5m])", "{{node}}", "A")],
                  unit="percent",
                  desc="PSI: share of time at least one task waited for CPU. Sustained >20% means the node is CPU-starved.")),
    ])

    # --- Workloads ------------------------------------------------------------------
    b.row("Workloads")
    b.line(8, [
        (12, b.ts("CPU by namespace (top 10, cores)",
                  [('topk(10, sum by (namespace) (rate(container_cpu_usage_seconds_total{container!="",image!=""}[5m])))',
                    "{{namespace}}", "A")])),
        (12, b.ts("Memory by namespace (top 10, working set)",
                  [('topk(10, sum by (namespace) (container_memory_working_set_bytes{container!="",image!=""}))',
                    "{{namespace}}", "A")],
                  unit="bytes")),
    ])
    b.line(9, [
        (24, b.bargauge("PVC used %", "100 * kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes",
                        "{{namespace}}/{{persistentvolumeclaim}}",
                        desc="local-path has no quota enforcement: a PVC can exceed 100% of its request and eat the node's disk.")),
    ])

    # --- Pod pressure (per-pod PSI + CPU throttling) --------------------------------
    # Which pods are STARVED, not merely busy. CPU% cannot tell a pod that is busy
    # from one that is waiting for CPU it is not getting; PSI can. Throttling says why:
    # high CPU waiting with high throttling = the pod's own CPU limit is too low; high
    # waiting with low throttling = the node is contended.
    b.row("Pod pressure")
    b.line(8, [
        (12, b.ts("Pods most stalled on CPU (% time, top 10)",
                  [('topk(10, 100 * sum by (namespace, pod) (rate(container_pressure_cpu_waiting_seconds_total{container!=""}[5m])))',
                    "{{namespace}}/{{pod}}", "A")],
                  unit="percent",
                  desc="PSI 'some': share of time at least one of the pod's tasks waited for CPU. Sustained >25% alerts (Pod CPU starved).")),
        (12, b.ts("Pods most CPU-throttled (% of periods, top 10)",
                  [('topk(10, 100 * sum by (namespace, pod) (rate(container_cpu_cfs_throttled_periods_total{container!=""}[5m]))'
                    ' / sum by (namespace, pod) (rate(container_cpu_cfs_periods_total{container!=""}[5m])))',
                    "{{namespace}}/{{pod}}", "A")],
                  unit="percent",
                  desc="Share of CFS periods in which the pod hit its CPU limit. High here plus high CPU stall = raise the limit.")),
    ])
    b.line(8, [
        (12, b.ts("Pods most stalled on memory (% time, top 10)",
                  [('topk(10, 100 * sum by (namespace, pod) (rate(container_pressure_memory_waiting_seconds_total{container!=""}[5m])))',
                    "{{namespace}}/{{pod}}", "A")],
                  unit="percent",
                  desc="Time spent reclaiming memory. Non-zero usually means the pod is at its memory limit and thrashing page cache.")),
        (12, b.ts("Pods most stalled on IO (% time, top 10)",
                  [('topk(10, 100 * sum by (namespace, pod) (rate(container_pressure_io_waiting_seconds_total{container!=""}[5m])))',
                    "{{namespace}}/{{pod}}", "A")],
                  unit="percent")),
    ])
    b.line(8, [
        (24, b.bargauge("Memory used vs limit (top 15)",
                        'topk(15, 100 * max by (namespace, pod, container) (container_memory_working_set_bytes{container!="",image!=""}'
                        ' / (container_spec_memory_limit_bytes{container!="",image!=""} > 0)))',
                        "{{namespace}}/{{pod}} ({{container}})",
                        steps=[("green", None), ("yellow", 80), ("red", 90)],
                        desc="Working set as a share of the container's memory limit. >90% for 15m alerts (Container near memory limit).")),
    ])

    # --- Control plane & GitOps -----------------------------------------------------
    b.row("Control plane & GitOps")
    b.line(8, [
        (12, b.ts("API server requests by code",
                  [("sum by (code) (rate(apiserver_request_total[5m]))", "{{code}}", "A")], unit="reqps")),
        (4, b.stat("API 5xx / s", 'sum(rate(apiserver_request_total{code=~"5.."}[5m])) or vector(0)',
                   unit="reqps", steps=[("green", None), ("orange", 0.1), ("red", 1)])),
        (4, b.stat("Argo apps Synced + Healthy",
                   'count(argocd_app_info{sync_status="Synced",health_status="Healthy"}) or vector(0)',
                   steps=[("blue", None)])),
        (4, b.stat("Argo apps NOT green",
                   'count(argocd_app_info{sync_status!="Synced"} or argocd_app_info{health_status!="Healthy"}) or vector(0)',
                   steps=[("green", None), ("red", 1)],
                   desc="The upgrade gate (scripts/hop-verify.sh) requires 0 here.")),
    ])
    b.line(6, [
        (24, b.table("Argo apps not Synced/Healthy",
                     'argocd_app_info{sync_status!="Synced"} or argocd_app_info{health_status!="Healthy"}',
                     ["name", "sync_status", "health_status", "dest_namespace"],
                     {"name": "App", "sync_status": "Sync", "health_status": "Health", "dest_namespace": "Namespace"})),
    ])

    return {"uid": "cluster-overview", "title": "Cluster Overview", "tags": ["kubernetes", "k3s", "cluster"],
            "timezone": "browser", "schemaVersion": 39, "version": 1, "editable": True, "refresh": "1m",
            "time": {"from": "now-6h", "to": "now"}, "panels": b.panels, "templating": {"list": []},
            "annotations": {"list": []}}


def render():
    body = json.dumps(build(), indent=2)
    indented = "\n".join("    " + line for line in body.split("\n"))
    return (HEADER + "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: grafana-dashboard-k8s-basic\n"
            "  namespace: logging\ndata:\n  cluster-overview.json: |\n" + indented + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 on drift")
    args = ap.parse_args()
    out = Path(args.repo_root) / OUT
    want = render()
    if args.check:
        have = out.read_text() if out.exists() else ""
        if have != want:
            print(f"{OUT} is out of date — run scripts/gen-cluster-overview-dashboard.py --repo-root .", file=sys.stderr)
            return 1
        print("Cluster Overview dashboard in sync.")
        return 0
    out.write_text(want)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
