#!/usr/bin/env python3
"""Generate (or --check / --export) this repo's Open Knowledge Format bundle.

This repo is an OKF v0.1 bundle in place: the root index.md is the bundle root
(it carries okf_version), every directory index.md is OKF's reserved directory
listing, and every base-apps/<app>/docs.md|runbook.md is an OKF concept document
(type/title/description + this repo's own agent-docs contract fields).

Three modes:

  --repo-root .            generate base-apps/index.md from doc frontmatter
  --check                  verify it is in sync; exit 1 on drift (CI gate)
  --export DIR             emit a standalone, portable bundle into DIR

WHY base-apps/index.md IS GENERATED:
  The per-app one-liner used to be hand-maintained in the index table, which
  drifted from reality (dex carried a full contract while its row still showed
  it as a stub). `description:` in docs.md frontmatter is now the single source
  and the table is derived, so the two cannot disagree.

WHY timestamp IS NOT STORED IN THE SOURCE FILES:
  OKF's `timestamp` means "last meaningful change". Writing it into docs.md
  would go stale the moment the file is committed, and a --check gate would then
  fail on every doc PR. Export derives it from `git log` instead, which is both
  accurate and churn-free. `last_reviewed` remains the separate human
  attestation (someone vouched for this), which git cannot infer.
"""
import argparse
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

GENERATED_MARKER = "<!-- GENERATED by scripts/gen-okf.py — do not edit by hand. -->"

INDEX_HEADER = """\
---
type: "Directory Index"
title: "base-apps"
description: "Directory listing for every Argo CD application: purpose, namespace, and its knowledge documents."
tags: [base-apps, argocd, index]
---

# base-apps Index

{marker}

One row per Argo CD app directory; doc links are relative to `base-apps/`.
Apps carrying the full agent-docs contract link to their documents; the rest are
stubs pending backfill (see `scripts/agent-docs-scope.txt`).

| app | description | namespace | docs | runbook | catalog |
|---|---|---|---|---|---|
"""


def _read_frontmatter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---"):
        raise ValueError(f"{path}: missing YAML frontmatter")
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"{path}: malformed frontmatter (no closing '---')")
    data = yaml.safe_load(parts[1])
    if not isinstance(data, dict):
        raise ValueError(f"{path}: frontmatter is not a mapping")
    return data


def _stubs(repo_root: Path) -> dict:
    path = repo_root / "scripts" / "okf-stubs.yaml"
    if not path.is_file():
        return {}
    return yaml.safe_load(path.read_text()) or {}


def _app_dirs(repo_root: Path) -> list[Path]:
    return sorted(d for d in (repo_root / "base-apps").iterdir() if d.is_dir())


def render_index(repo_root: Path) -> str:
    """Build base-apps/index.md from each app's docs.md frontmatter."""
    stubs = _stubs(repo_root)
    rows = []
    for app_dir in _app_dirs(repo_root):
        app = app_dir.name
        docs, runbook = app_dir / "docs.md", app_dir / "runbook.md"
        catalog = app_dir / "catalog-info.yaml"

        if docs.is_file():
            fm = _read_frontmatter(docs)
            description = str(fm.get("description", "")).strip()
            namespace = str(fm.get("namespace", "")).strip()
        else:
            stub = stubs.get(app) or {}
            description = str(stub.get("description", "")).strip()
            namespace = str(stub.get("namespace", "")).strip()

        def link(path: Path) -> str:
            return f"[{path.name}]({app}/{path.name})" if path.is_file() else ""

        rows.append(
            f"| {app} | {description} | {namespace} | "
            f"{link(docs)} | {link(runbook)} | {link(catalog)} |"
        )
    return INDEX_HEADER.format(marker=GENERATED_MARKER) + "\n".join(rows) + "\n"


def check(repo_root: Path) -> list[str]:
    """Return drift/error messages (empty == in sync)."""
    problems = []
    index = repo_root / "base-apps" / "index.md"
    try:
        want = render_index(repo_root)
    except ValueError as exc:
        return [str(exc)]
    if not index.is_file():
        problems.append("base-apps/index.md: missing (run gen-okf.py to create)")
    elif index.read_text() != want:
        problems.append("base-apps/index.md: out of sync (run gen-okf.py)")

    root = repo_root / "index.md"
    if not root.is_file():
        problems.append("index.md: missing OKF bundle root")
    else:
        try:
            if not _read_frontmatter(root).get("okf_version"):
                problems.append("index.md: bundle root must declare okf_version")
        except ValueError as exc:
            problems.append(str(exc))
    return problems


def write(repo_root: Path) -> int:
    index = repo_root / "base-apps" / "index.md"
    want = render_index(repo_root)
    if index.is_file() and index.read_text() == want:
        return 0
    index.write_text(want)
    return 1


def _git_timestamp(repo_root: Path, rel: str) -> str | None:
    """ISO 8601 commit time of the last change to rel, or None if untracked."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cI", "--", rel],
            cwd=repo_root, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    return out or None


def _with_timestamp(text: str, stamp: str) -> str:
    """Insert an OKF `timestamp:` as the last frontmatter key."""
    head, fm, body = text.split("---", 2)
    fm = fm.rstrip("\n")
    return f"{head}---{fm}\ntimestamp: {stamp}\n---{body}"


def export(repo_root: Path, dest: Path) -> int:
    """Emit a standalone OKF bundle: navigation + concept docs, no manifests.

    Directory structure mirrors the repo so intra-bundle markdown links keep
    resolving. `sources:` entries still point at the origin repo, which OKF
    consumers must tolerate as external references.
    """
    if dest.exists():
        shutil.rmtree(dest)
    (dest / "base-apps").mkdir(parents=True)

    copied = 0
    for rel in ("index.md", "terraform/index.md", "docs/index.md"):
        src = repo_root / rel
        if not src.is_file():
            continue
        out = dest / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        stamp = _git_timestamp(repo_root, rel)
        text = src.read_text()
        out.write_text(_with_timestamp(text, stamp) if stamp else text)
        copied += 1

    (dest / "base-apps" / "index.md").write_text(render_index(repo_root))
    copied += 1

    for app_dir in _app_dirs(repo_root):
        for name in ("docs.md", "runbook.md"):
            src = app_dir / name
            if not src.is_file():
                continue
            rel = f"base-apps/{app_dir.name}/{name}"
            out = dest / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            stamp = _git_timestamp(repo_root, rel)
            text = src.read_text()
            out.write_text(_with_timestamp(text, stamp) if stamp else text)
            copied += 1
    return copied


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate this repo's OKF bundle.")
    ap.add_argument("--repo-root", default=".", type=Path)
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 on drift")
    ap.add_argument("--export", metavar="DIR", type=Path,
                    help="write a standalone portable bundle to DIR")
    args = ap.parse_args()
    repo_root = args.repo_root.resolve()

    if args.export:
        n = export(repo_root, args.export.resolve())
        print(f"Exported {n} document(s) to {args.export}")
        return 0

    if args.check:
        problems = check(repo_root)
        if problems:
            print("OKF bundle out of sync:")
            for p in problems:
                print(f"  {p}")
            print(f"\n{len(problems)} problem(s). Run: python3 scripts/gen-okf.py --repo-root .")
            return 1
        print(f"OKF bundle in sync ({len(_app_dirs(repo_root))} app directories).")
        return 0

    n = write(repo_root)
    print(f"Generated/updated {n} file(s) ({len(_app_dirs(repo_root))} app directories).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
