#!/usr/bin/env python3
"""Generate (or --check / --export) this repo's Open Knowledge Format bundle.

The repo holds OKF v0.2 knowledge documents in place: the root index.md is the
bundle root (it carries okf_version), and every base-apps/<app>/docs.md and
runbook.md is an OKF concept document (type/title/description plus this
repo's own agent-docs contract fields). The repo as a whole is not a
conformant bundle (README.md, CLAUDE.md and most of docs/ have no frontmatter,
and the in-repo index files carry frontmatter and tables). --export is what
emits a strictly conformant one.

Three modes:

  --repo-root .            generate base-apps/index.md from doc frontmatter
  --check                  verify it is in sync; exit 1 on drift (CI gate)
  --export DIR             emit a standalone, OKF v0.2-conformant bundle into DIR

WHY base-apps/index.md IS GENERATED:
  The per-app one-liner used to be hand-maintained in the index table, which
  drifted from reality (dex carried a full contract while its row still showed
  it as a stub). `description:` in docs.md frontmatter is now the single source
  and the table is derived, so the two cannot disagree.

WHY THE TRUST FIELDS ARE DERIVED AT EXPORT, NOT STORED:
  OKF v0.2's `generated: {by, at}` means "who last changed this, and when".
  Writing it into docs.md would go stale the moment the file is committed, and
  a --check gate would then fail on every doc PR. Export reads it from git
  instead. `last_reviewed` stays the one hand-written trust field; export turns
  it into `verified` and `stale_after`. Who verified is read from the commit
  that last changed the `last_reviewed:` line (see _verifier).
"""
import argparse
import re
import shutil
import subprocess
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

import yaml

GENERATED_MARKER = "<!-- GENERATED by scripts/gen-okf.py — do not edit by hand. -->"

OKF_VERSION = "0.2"

# Matches validate-agent-docs.py's default --max-age-days: a doc is stale 180
# days after its last review, so export writes that instant as `stale_after`.
STALE_AFTER_DAYS = 180

BASE_APPS_DESCRIPTION = (
    "Directory listing for every Argo CD application: purpose, namespace, "
    "and its knowledge documents.")

# Hand-written directory indexes. They carry frontmatter and prose, which OKF
# §8 does not allow in an index.md, so export moves each one to overview.md
# and writes a conformant listing in its place.
HAND_WRITTEN_INDEXES = ("terraform/index.md", "ansible/index.md", "docs/index.md")

INDEX_HEADER = """\
---
type: "Directory Index"
title: "base-apps"
description: "{description}"
tags: [base-apps, argocd, index]
---

# base-apps Index

{marker}

One row per Argo CD app directory; doc links are relative to `base-apps/`.
Apps carrying the full agent-docs contract link to their documents; the rest are
stubs pending backfill (see `scripts/agent-docs-scope.txt`).

| app | description | namespace | docs | runbook | catalog |
|---|---|---|---|---|---|
"""


def _read_frontmatter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---"):
        raise ValueError(f"{path}: missing YAML frontmatter")
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"{path}: malformed frontmatter (no closing '---')")
    data = yaml.safe_load(parts[1])
    if not isinstance(data, dict):
        raise ValueError(f"{path}: frontmatter is not a mapping")
    return data


def _stubs(repo_root: Path) -> dict:
    path = repo_root / "scripts" / "okf-stubs.yaml"
    if not path.is_file():
        return {}
    return yaml.safe_load(path.read_text()) or {}


def _app_dirs(repo_root: Path) -> list[Path]:
    return sorted(d for d in (repo_root / "base-apps").iterdir() if d.is_dir())


def render_index(repo_root: Path) -> str:
    """Build base-apps/index.md from each app's docs.md frontmatter."""
    stubs = _stubs(repo_root)
    rows = []
    for app_dir in _app_dirs(repo_root):
        app = app_dir.name
        docs, runbook = app_dir / "docs.md", app_dir / "runbook.md"
        catalog = app_dir / "catalog-info.yaml"

        if docs.is_file():
            fm = _read_frontmatter(docs)
            description = str(fm.get("description", "")).strip()
            namespace = str(fm.get("namespace", "")).strip()
        else:
            stub = stubs.get(app) or {}
            description = str(stub.get("description", "")).strip()
            namespace = str(stub.get("namespace", "")).strip()

        def link(path: Path) -> str:
            return f"[{path.name}]({app}/{path.name})" if path.is_file() else ""

        rows.append(
            f"| {app} | {description} | {namespace} | "
            f"{link(docs)} | {link(runbook)} | {link(catalog)} |"
        )
    header = INDEX_HEADER.format(marker=GENERATED_MARKER, description=BASE_APPS_DESCRIPTION)
    return header + "\n".join(rows) + "\n"


def check(repo_root: Path) -> list[str]:
    """Return drift/error messages (empty == in sync)."""
    problems = []
    index = repo_root / "base-apps" / "index.md"
    try:
        want = render_index(repo_root)
    except ValueError as exc:
        return [str(exc)]
    if not index.is_file():
        problems.append("base-apps/index.md: missing (run gen-okf.py to create)")
    elif index.read_text() != want:
        problems.append("base-apps/index.md: out of sync (run gen-okf.py)")

    root = repo_root / "index.md"
    if not root.is_file():
        problems.append("index.md: missing OKF bundle root")
    else:
        try:
            declared = _read_frontmatter(root).get("okf_version")
        except ValueError as exc:
            problems.append(str(exc))
        else:
            if str(declared) != OKF_VERSION:
                problems.append(
                    f"index.md: bundle root must declare okf_version {OKF_VERSION!r}, got {declared!r}")
    return problems


def write(repo_root: Path) -> int:
    index = repo_root / "base-apps" / "index.md"
    want = render_index(repo_root)
    if index.is_file() and index.read_text() == want:
        return 0
    index.write_text(want)
    return 1


# --- export ------------------------------------------------------------------

def _git(repo_root: Path, *args: str) -> str | None:
    try:
        out = subprocess.run(
            ["git", *args], cwd=repo_root, capture_output=True, text=True, check=True,
        ).stdout.rstrip("\n")  # not strip(): it also eats the \x1e/\x1f separators below
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    return out or None


# Fields are \x1e-separated; trailer values within a field are \x1f-separated.
_COMMIT_FORMAT = (
    "%cI%x1e%an%x1e%ae%x1e"
    "%(trailers:key=Co-Authored-By,valueonly,separator=%x1f)%x1e"
    "%(trailers:key=Reviewed-by,valueonly,separator=%x1f)")


def _last_commit(repo_root: Path, rel: str, *pickaxe: str) -> dict | None:
    """The last commit touching rel (narrowed by e.g. -G<regex>), or None."""
    out = _git(repo_root, "log", "-1", f"--format={_COMMIT_FORMAT}", *pickaxe, "--", rel)
    if not out:
        return None
    at, name, email, coauthors, reviewers = out.split("\x1e")

    def values(field: str) -> list[str]:
        return [v.strip() for v in field.split("\x1f") if v.strip()]

    return {"at": at, "name": name, "email": email,
            "coauthors": values(coauthors), "reviewers": values(reviewers)}


def _person(ident: str) -> str:
    """'Name <user@host>' or 'user@host' -> OKF actor 'human:user'."""
    email = ident.rsplit("<", 1)[-1].rstrip(">").strip()
    return f"human:{email.split('@', 1)[0]}"


def _writer(commit: dict) -> str:
    """OKF actor (§7) for whoever wrote a commit's content.

    A Claude co-author trailer means an agent wrote it, whoever committed:
    'Claude Opus 5.5' -> 'claude-code/claude-opus-5.5'. A GitHub bot is a
    process. Anyone else is a human, identified by their email's local part.
    """
    for coauthor in commit["coauthors"]:
        name = coauthor.split("<", 1)[0].strip()
        if name.lower().startswith("claude"):
            return "claude-code/" + "-".join(name.lower().split())
    if commit["name"].endswith("[bot]"):
        return f"process:{commit['name'][:-len('[bot]')]}"
    return _person(commit["email"])


def _verifier(commit: dict) -> str:
    """OKF actor for whoever vouched for a `last_reviewed` bump.

    OKF requires the `human:` prefix to mean a person actually confirmed the
    content (it is what makes a doc "human-reviewed"). A bump made in an
    agent-written commit is therefore an agent's check unless the commit
    carries a `Reviewed-by:` trailer naming the person who read it.
    """
    if commit["reviewers"]:
        return _person(commit["reviewers"][0])
    return _writer(commit)


def _source_base_url(repo_root: Path) -> str | None:
    """GitHub blob URL for HEAD, so exported sources point at what was read."""
    remote = _git(repo_root, "remote", "get-url", "origin")
    head = _git(repo_root, "rev-parse", "HEAD")
    if not remote or not head:
        return None
    m = re.match(r"(?:git@github\.com:|https://github\.com/)([^/]+/[^/]+?)(?:\.git)?/?$", remote)
    return f"https://github.com/{m.group(1)}/blob/{head}" if m else None


def _source_id(path: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", path.lower()).strip("-")


def _sources(repo_root: Path, sources: list, base_url: str | None) -> list[dict]:
    """Contract `sources` (bare paths or {id, resource, title}) -> OKF §5.1 entries.

    A repo path becomes a URL into the origin repo at HEAD (a path relative to
    the bundle would not resolve: the manifests are not exported) and gains
    `last_modified` from git, so a consumer can see a source that changed
    after the doc was last verified.
    """
    entries = []
    for src in sources or []:
        given = dict(src) if isinstance(src, dict) else {"resource": str(src)}
        resource = given["resource"]
        entry = {"id": given.get("id") or _source_id(resource), "resource": resource}
        if "title" in given:
            entry["title"] = given["title"]
        if not resource.startswith(("http://", "https://")):
            if base_url:
                entry["resource"] = f"{base_url}/{resource}"
            modified = _git(repo_root, "log", "-1", "--format=%cI", "--", resource)
            if modified:
                entry["last_modified"] = modified
        entries.append(entry)
    return entries


def _as_date(value) -> date:
    return value if isinstance(value, date) else datetime.strptime(str(value), "%Y-%m-%d").date()


def _split(text: str) -> tuple[dict, str]:
    _, fm, body = text.split("---", 2)
    return yaml.safe_load(fm) or {}, body


def _render(fm: dict, body: str) -> str:
    dumped = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, width=1000,
                            default_flow_style=False)
    return f"---\n{dumped}---{body}"


def _concept(repo_root: Path, rel: str, base_url: str | None, type_override: str | None = None) -> str:
    """One concept document with OKF v0.2 provenance, trust and lifecycle."""
    fm, body = _split((repo_root / rel).read_text())
    fm.pop("timestamp", None)  # v0.1; superseded by generated.at
    if type_override:
        fm["type"] = type_override
    if "sources" in fm:
        fm["sources"] = _sources(repo_root, fm["sources"], base_url)

    changed = _last_commit(repo_root, rel)
    if changed:
        fm["generated"] = {"by": _writer(changed), "at": changed["at"]}
    if "last_reviewed" in fm:
        reviewed = _as_date(fm["last_reviewed"])
        bump = _last_commit(repo_root, rel, "-G^last_reviewed:")
        if bump:
            fm["verified"] = {"by": _verifier(bump), "at": f"{reviewed.isoformat()}T00:00:00Z"}
        stale = reviewed + timedelta(days=STALE_AFTER_DAYS)
        fm["stale_after"] = f"{stale.isoformat()}T00:00:00Z"
    return _render(fm, body)


def _listing(sections: list[tuple[str, list[tuple[str, str, str]]]]) -> str:
    """An OKF §8 index body: headed sections of '* [Title](url) - description'."""
    blocks = []
    for heading, entries in sections:
        lines = [f"# {heading}", ""]
        lines += [f"* [{title}]({url})" + (f" - {desc}" if desc else "")
                  for title, url, desc in entries]
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks) + "\n"


def _entry(fm: dict, url: str, fallback_title: str) -> tuple[str, str, str]:
    return (str(fm.get("title") or fallback_title), url, str(fm.get("description") or "").strip())


def export(repo_root: Path, dest: Path) -> int:
    """Emit a standalone OKF v0.2 bundle: navigation + concept docs, no manifests.

    Directory structure mirrors the repo, so links between documents keep
    resolving. Index files are rewritten as §8 listings; the prose of the
    in-repo root and hand-written indexes moves to an overview.md concept next
    to them. Returns the number of files written.
    """
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    base_url = _source_base_url(repo_root)
    written = 0

    def emit(rel: str, text: str):
        nonlocal written
        out = dest / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
        written += 1

    root_sections = []
    if (repo_root / "index.md").is_file():
        emit("overview.md", _concept(repo_root, "index.md", base_url))
        fm = _read_frontmatter(repo_root / "index.md")
        root_sections.append(("Platform", [_entry(fm, "overview.md", "Overview")]))

    directories = [("base-apps", "base-apps/index.md", BASE_APPS_DESCRIPTION)]
    for rel in HAND_WRITTEN_INDEXES:
        if not (repo_root / rel).is_file():
            continue
        folder = rel.rsplit("/", 1)[0]
        fm = _read_frontmatter(repo_root / rel)
        emit(f"{folder}/overview.md",
             _concept(repo_root, rel, base_url, type_override="Directory Overview"))
        title, _, desc = _entry(fm, "overview.md", folder)
        emit(rel, _listing([(title, [(title, "overview.md", desc)])]))
        directories.append((title, rel, desc))
    root_sections.append(("Directories", directories))
    emit("index.md", f'---\nokf_version: "{OKF_VERSION}"\n---\n\n' + _listing(root_sections))

    guides, runbooks = [], []
    for app_dir in _app_dirs(repo_root):
        for name, group in (("docs.md", guides), ("runbook.md", runbooks)):
            if not (app_dir / name).is_file():
                continue
            rel = f"base-apps/{app_dir.name}/{name}"
            emit(rel, _concept(repo_root, rel, base_url))
            group.append(_entry(_read_frontmatter(app_dir / name),
                                f"{app_dir.name}/{name}", app_dir.name))
    sections = [(h, e) for h, e in (("App guides", guides), ("Runbooks", runbooks)) if e]
    emit("base-apps/index.md", _listing(sections) if sections else "# base-apps\n")
    return written


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate this repo's OKF bundle.")
    ap.add_argument("--repo-root", default=".", type=Path)
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 on drift")
    ap.add_argument("--export", metavar="DIR", type=Path,
                    help="write a standalone OKF v0.2 bundle to DIR")
    args = ap.parse_args()
    repo_root = args.repo_root.resolve()

    if args.export:
        n = export(repo_root, args.export.resolve())
        print(f"Exported {n} document(s) to {args.export}")
        return 0

    if args.check:
        problems = check(repo_root)
        if problems:
            print("OKF bundle out of sync:")
            for p in problems:
                print(f"  {p}")
            print(f"\n{len(problems)} problem(s). Run: python3 scripts/gen-okf.py --repo-root .")
            return 1
        print(f"OKF bundle in sync ({len(_app_dirs(repo_root))} app directories).")
        return 0

    n = write(repo_root)
    print(f"Generated/updated {n} file(s) ({len(_app_dirs(repo_root))} app directories).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
