apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: mysql-provider
spec:
  credentials:
    source: MySQLConnectionSecret
    connectionSecretRef:
      namespace: crossplane-system
      name: mysql-credentials
  tls: preferred