apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: mysql-provider
  namespace: crossplane-system
spec:
  credentials:
    source: MySQLConnectionSecret
    connectionSecretRef:
      namespace: mysql
      name: mysql-credentials
  # Connection configuration
  endpoint: mysql.mysql.svc.cluster.local:3306
  tls: "skip-verify"