apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecr-test
  template:
    metadata:
      labels:
        app: ecr-test
    spec:
      nodeSelector:
        node.kubernetes.io/workload: application
      containers:
      - name: ecr-test
        image: 852893458518.dkr.ecr.us-east-2.amazonaws.com/chores-tracker:5.3.0
        command: ["sleep", "infinity"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
