apiVersion: v1
kind: Service
metadata:
  name: qwen
  namespace: qwen
  labels:
    app: qwen
spec:
  selector:
    app: qwen
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
