apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: asela-testmysql-mysql-db
  description: MySQL database for asela-testmysql
  annotations:
    backstage.io/kubernetes-id: asela-testmysql
    backstage.io/kubernetes-namespace: asela-testmysql
spec:
  type: database
  owner: group:default/platform-team
  system: system:default/examples
  lifecycle: development