apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: asela-test3-secret
  namespace: asela-test3
  labels:
    app.kubernetes.io/name: asela-test3
    app.kubernetes.io/instance: asela-test3-mysql
    app.kubernetes.io/component: database-secret
    app.kubernetes.io/part-of: asela-test3
    environment: development
    backstage.io/kubernetes-id: asela-test3
  annotations:
    backstage.io/kubernetes-id: asela-test3
    backstage.io/kubernetes-namespace: asela-test3
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: asela-test3-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: asela-test3
        property: DB_PASSWORD
