apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: asela-test3
  labels:
    app.kubernetes.io/name: asela-test3
    app.kubernetes.io/instance: asela-test3-vault
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: asela-test3
    environment: development
    backstage.io/kubernetes-id: asela-test3
  annotations:
    backstage.io/kubernetes-id: asela-test3
    backstage.io/kubernetes-namespace: asela-test3
spec:
  provider:
    vault:
      server: 'http://vault.vault.svc.cluster.local:8200'
      path: 'secret'
      version: 'v2'
      auth:
        tokenSecretRef:
          name: 'vault-token'
          key: 'token'
