apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: asela3-secret
  namespace: asela3
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: asela3-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: asela3
        property: DB_PASSWORD