apiVersion: platform.io/v1alpha1
kind: MySQLDatabase
metadata:
  name: asela3
  namespace: asela3
spec:
  compositionRef:
    name: xmysqldatabase.platform.io
  parameters:
    databaseName: asela3db
    username: asela3user
    userNamespace: asela3
    databaseNamespace: asela3
    privileges:
      ["SELECT","INSERT","UPDATE","DELETE"]
    passwordSecretRef:
      name: asela3-secret
      key: DB_PASSWORD
      namespace: asela3
  writeConnectionSecretToRef:
    name: asela3-connection