apiVersion: v1
kind: ServiceAccount
metadata:
  name: route53-updater
  namespace: route53-updater
  labels:
    app: route53-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: route53-updater
  name: route53-updater-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: route53-updater-binding
  namespace: route53-updater
subjects:
- kind: ServiceAccount
  name: route53-updater
  namespace: route53-updater
roleRef:
  kind: Role
  name: route53-updater-role
  apiGroup: rbac.authorization.k8s.io