apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml  # Your Rollout resource
configMapGenerator:
  - name: blue-config
    literals:
      - key1=value1
      - key2=value2
  - name: green-config
    literals:
      - key1=value3
      - key2=value4
