apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-nginx-rollout
  namespace: argo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-nginx
  template:
    metadata:
      labels:
        app: blue-green-nginx
    spec:
      containers:
      - name: python-server
        image: python:3.8-slim
        command: ["sh", "-c"]
        args:
          - |
            echo '<h1>This is the ${APP_COLOR} version of the application</h1>' > /app/index.html && \
            python -m http.server 80 -d /app
        env:
        - name: APP_COLOR
          value: "blue" # Update this for green version as well
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: blue-nginx-service
      previewService: green-nginx-service
      autoPromotionEnabled: false
