apiVersion: v1
kind: Service
metadata:
  name: blue-nginx-service
  namespace: argo-cd
spec:
  selector:
    app: blue-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  nodePort: 30090
---
apiVersion: v1
kind: Service
metadata:
  name: green-nginx-service
  namespace: argo-cd
spec:
  selector:
    app: green-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  nodePort: 30091