apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-agent-secret
  namespace: ai-platform
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: argocd-agent-secret
    creationPolicy: Owner
  data:
    - secretKey: ARGOCD_USERNAME
      remoteRef:
        key: ai-platform/argocd-agent
        property: ARGOCD_USERNAME
    - secretKey: ARGOCD_PASSWORD
      remoteRef:
        key: ai-platform/argocd-agent
        property: ARGOCD_PASSWORD
    - secretKey: ARGOCD_API_URL
      remoteRef:
        key: ai-platform/argocd-agent
        property: ARGOCD_API_URL
    - secretKey: ARGOCD_INSECURE
      remoteRef:
        key: ai-platform/argocd-agent
        property: ARGOCD_INSECURE
