apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llm-secret
  namespace: ai-platform
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: llm-secret
    creationPolicy: Owner
  data:
    - secretKey: LLM_PROVIDER
      remoteRef:
        key: ai-platform/llm
        property: LLM_PROVIDER
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: ai-platform/llm
        property: ANTHROPIC_API_KEY
    - secretKey: ANTHROPIC_MODEL_NAME
      remoteRef:
        key: ai-platform/llm
        property: ANTHROPIC_MODEL_NAME
