apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: 852893458518.dkr.ecr.us-east-2.amazonaws.com/backstage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgresql-credentials
            - secretRef:
                name: backstage-secrets
          volumeMounts:
            - name: config-volume
              mountPath: /app/app-config.yaml
              subPath: app-config.yaml
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: backstage-config