apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: backstage
        property: postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: backstage
        property: postgres-password
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: backstage
        property: github-token
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: backstage
        property: github-oauth-client-id
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: backstage
        property: github-oauth-client-secret
    - secretKey: K8S_CLUSTER_URL
      remoteRef:
        key: backstage
        property: k8s-cluster-url
    - secretKey: K8S_SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: backstage
        property: k8s-service-account-token
