apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backstage-ingress
  namespace: backstage
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`backstage.arigsela.com`)
      services:
        - name: backstage
          port: 80