apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.name }}-config
  namespace: ${{ values.namespace }}
data:
{% for item in values.configData %}  ${{ item.key }}: "${{ item.value }}"
{% endfor %}