apiVersion: platform.io/v1alpha1
kind: MySQLDatabase
metadata:
  name: test-argocd
  namespace: test-argocd
  labels:
    app.kubernetes.io/name: test-argocd
    app.kubernetes.io/instance: test-argocd-mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: test-argocd
    environment: development
    backstage.io/kubernetes-id: test-argocd
  annotations:
    # These annotations are used by the kubernetes-ingestor to discover this resource
    backstage.io/kubernetes-id: test-argocd
    backstage.io/kubernetes-namespace: test-argocd
spec:
  compositionRef:
    name: xmysqldatabases.platform.io
  parameters:
    # Database configuration
    databaseName: test-argocddb
    storageSize: 1Gi
    
    # User configuration
    username: test-argocduser
    privileges: ["SELECT","INSERT","UPDATE","DELETE"]
    
    # Connection secret configuration
    connectionSecretName: test-argocd-connection
    connectionSecretNamespace: test-argocd
    
    # Resource class based on environment
    resourceClass: development