apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: test-argocd
  labels:
    app.kubernetes.io/name: test-argocd
    app.kubernetes.io/instance: test-argocd-vault
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: test-argocd
    environment: development
    backstage.io/kubernetes-id: test-argocd
  annotations:
    backstage.io/kubernetes-id: test-argocd
    backstage.io/kubernetes-namespace: test-argocd
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"