apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: asela6
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
      path: secret
      server: http://vault.vault.svc.cluster.local:8200
      version: v2