apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: logging
  namespace: logging
  annotations:
    agent-docs/path: docs.md
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app in (grafana,loki,prometheus,alloy)'
    backstage.io/kubernetes-namespace: logging
  tags: [loki, grafana, prometheus, alloy]
spec:
  type: service
  lifecycle: production
  owner: group:default/platform
  system: default/platform-observability
  dependsOn:
    - resource:vault/vault
